# Generated by Django 4.1.6 on 2024-04-02 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='texts',
            name='similarity_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
